### ISSUE TITLE
How do you create the bam file and why?

### ISSUE THREAD

**Issue by AntonioBaeza** [o-william-white/circos_plot_organelle#4]
Nice depiction of a circular mitogenome map. Can I ask how do you create the bam file and why? Thanks!

**Comment by o-william-white** [comment]
Hi @AntonioBaeza. The bam file was created by mapping the reads which were used to create the mitochondrial assembly to the assembled mitochondrial genome. Any read mapping tool should be fine (bwa mem, bowtie2 or minimap for example). This bam file is then used to plot read coverage inside the annotations. I found this is useful to visualise regions with low coverage which often break the assembly. Hope this helps and let me know if you have any more questions.

**Comment by AntonioBaeza** [comment]
Thank you! I will give it a try! Best, Antonio

**Comment by AntonioBaeza** [comment]
(circos_plot_organelle) ant@hillary:~/circos_plot_organelle$ python circos_plot_organelle.py --fasta Jasus_frontalis.fasta --bam fastpuncseqsMITOmapped.bam --bed JfrontalisBEDmodified.bed --window 50
Running samtools coverage
samtools depth: Data is not position sorted
Traceback (most recent call last):
  File "/home/ant/circos_plot_organelle/circos_plot_organelle.py", line 63, in <module>
    for line in subprocess.check_output(["samtools", "depth",  "-a", args.bam]).decode().split("\n"):
                ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/miniconda3/envs/circos_plot_organelle/lib/python3.13/subprocess.py", line 472, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
               **kwargs).stdout
               ^^^^^^^^^
  File "/home/ant/miniconda3/envs/circos_plot_organelle/lib/python3.13/subprocess.py", line 577, in run
    raise CalledProcessError(retcode, process.args,
                             output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['samtools', 'depth', '-a', 'fastpuncseqsMITOmapped.bam']' returned non-zero exit status 1.
(circos_plot_organelle) ant@hillary:~/circos_plot_organelle$
(circos_plot_organelle) ant@hillary:~/circos_plot_organelle$
(circos_plot_organelle) ant@hillary:~/circos_plot_organelle$
(circos_plot_organelle) ant@hillary:~/circos_plot_organelle$
(circos_plot_organelle) ant@hillary:~/circos_plot_organelle$


Any chance you can provide more details about the creation of the bam file? Thank you

**Comment by AntonioBaeza** [comment]
I mapped with HISAT2. Usual mapping. Looks like I need to organize the bam file with samtools, but, any detail will be appreciated.

**Comment by AntonioBaeza** [comment]
Also, when running the example, I also get errors:

(circos_plot_organelle) ant@hillary:~/circos_plot_organelle$ python circos_plot_organelle.py \
>    --fasta example_data/010210013_StH_H3.fasta \
>    --bam example_data/010210013_StH_H3.bam \
>    --bed example_data/010210013_StH_H3.bed \
>    --window 50
Running samtools coverage
Calculating mean coverage in 50 bp windows
Calculating GC content in 50 bp windows
Running trf
**********

Tandem Repeats Finder, Version 4.09
Copyright (C) Dr. Gary Benson 1999-2012. All rights reserved.

Loading sequence...
Allocating Memory...
Initializing data structures...
Computing TR Model Statistics...
Scanning...
.....................

Freeing Memory...
Resolving output...
Done.

**********
Finished trf
Calculating N content in 50 bp windows
Writing karyotype.txt
Writing ideogram.conf
Writing ticks.conf
Writing circos.conf
Writing annotations lables and gene files
Running circos
**********


*** REQUIRED MODULE(S) MISSING OR OUT-OF-DATE ***

You are missing one or more Perl modules, require newer versions, or some modules failed to load. Use CPAN to install it as described in this tutorial

http://www.circos.ca/documentation/tutorials/configuration/perl_and_modules

missing GD
  error Can't locate GD.pm in @INC (you may need to install the GD module) (@INC contains: /home/ant/miniconda3/envs/circos_plot_organelle/bin/lib /home/ant/miniconda3/envs/circos_plot_organelle/bin/../lib /home/ant/miniconda3/envs/circos_plot_organelle/bin /home/ant/miniconda3/envs/circos_plot_organelle/lib/perl5/5.32/site_perl /home/ant/miniconda3/envs/circos_plot_organelle/lib/perl5/site_perl /home/ant/miniconda3/envs/circos_plot_organelle/lib/perl5/5.32/vendor_perl /home/ant/miniconda3/envs/circos_plot_organelle/lib/perl5/vendor_perl /home/ant/miniconda3/envs/circos_plot_organelle/lib/perl5/5.32/core_perl /home/ant/miniconda3/envs/circos_plot_organelle/lib/perl5/core_perl .) at (eval 39) line 1.
missing GD::Polyline
  error Can't locate GD/Polyline.pm in @INC (you may need to install the GD::Polyline module) (@INC contains: /home/ant/miniconda3/envs/circos_plot_organelle/bin/lib /home/ant/miniconda3/envs/circos_plot_organelle/bin/../lib /home/ant/miniconda3/envs/circos_plot_organelle/bin /home/ant/miniconda3/envs/circos_plot_organelle/lib/perl5/5.32/site_perl /home/ant/miniconda3/envs/circos_plot_organelle/lib/perl5/site_perl /home/ant/miniconda3/envs/circos_plot_organelle/lib/perl5/5.32/vendor_perl /home/ant/miniconda3/envs/circos_plot_organelle/lib/perl5/vendor_perl /home/ant/miniconda3/envs/circos_plot_organelle/lib/perl5/5.32/core_perl /home/ant/miniconda3/envs/circos_plot_organelle/lib/perl5/core_perl .) at (eval 40) line 1.

**********
Finished circos
Complete!
(circos_plot_organelle) ant@hillary:~/circos_plot_organelle$ ll
total 8664
drwxrwxr-x  5 ant ant    4096 Nov 19 09:19 ./
drwxr-xr-x 77 ant ant    4096 Nov 19 09:06 ../
-rw-rw-r--  1 ant ant    1359 Nov 19 09:19 010210013_StH_H3.fasta.2.7.7.80.10.50.500.dat
-rw-rw-r--  1 ant ant   16186 Nov 19 09:19 010210013_StH_H3.fasta.2.7.7.80.10.50.500.mask
-rw-rw-r--  1 ant ant     921 Nov 19 09:19 circos.conf
-rw-rw-r--  1 ant ant    7163 Nov 19 09:06 circos_plot_organelle.py
drwxrwxr-x  2 ant ant     141 Nov 19 09:19 data/
drwxrwxr-x  2 ant ant     130 Nov 19 09:06 example_data/
-rw-rw-r--  1 ant ant 8787718 Nov 18 21:35 fastpuncseqsMITOmapped.bam
drwxrwxr-x  8 ant ant    4096 Nov 19 09:06 .git/
-rw-rw-r--  1 ant ant     412 Nov 19 09:19 ideogram.conf
-rw-rw-r--  1 ant ant   15557 Sep 26 17:11 Jasus_frontalis.fasta
-rw-rw-r--  1 ant ant    1589 Nov 18 21:59 JfrontalisBEDmodified.bed
-rw-rw-r--  1 ant ant      59 Nov 19 09:19 karyotype.txt
-rw-rw-r--  1 ant ant     978 Nov 19 09:06 README.md
-rw-rw-r--  1 ant ant     437 Nov 19 09:19 ticks.conf
(circos_plot_organelle) ant@hillary:~/circos_plot_organelle$
(circos_plot_organelle) ant@hillary:~/circos_plot_organelle$
